#!/bin/bash

TRANSFORM_SCRIPT="/etc/perfsonar/psconfig/transforms.d/latency-testports.json"

#set powstream test ports if no default parameters
TESTPORTS=`grep -m 1 '^testports' /etc/owamp-server/owamp-server.conf | cut -f2 -d " "`
if [ -n "$TESTPORTS" ]; then
    IFS='-' read -ra PORT_RANGE <<< "$TESTPORTS"
    if [ -n "${PORT_RANGE[0]}" ] && [ -n "${PORT_RANGE[1]}" ]; then
        cat >${TRANSFORM_SCRIPT} <<EOF
{
    "script": ".tests |= map_values(if .type == \"latencybg\" or .type == \"latency\" then .spec.\"data-ports\" |= {\"lower\": ${PORT_RANGE[0]}, \"upper\": ${PORT_RANGE[1]}} else . end)"
}
EOF
    fi 
fi
