#!/bin/bash

#######################
# Remove SSL* settings from VirtualHost on install then leave alone on future 
# updates. Settings will be in apache-security.conf but if someone wants 
# to override those settings then they can do so in ssl.comnf after first install
#######################
# RedHat
if [ "$1" == "new" ]; then
    if [ -f /etc/httpd/conf.d/ssl.conf ]; then
        sed -i 's|^SSLProtocol\(.*\)|#SSLProtocol\1|g' /etc/httpd/conf.d/ssl.conf
        sed -i 's|^SSLCipherSuite\(.*\)|#SSLCipherSuite\1|g'  /etc/httpd/conf.d/ssl.conf
    fi
fi
# Debian/Ubuntu
for CONF in /etc/apache2/sites-available/{default-ssl,default-ssl.conf}; do
    if [ -f $CONF ]; then
        sed -i 's|^\([[:space:]]*\)SSLProtocol|\1#SSLProtocol|g' $CONF
        sed -i 's|^\([[:space:]]*\)SSLCipherSuite|\1#SSLCipherSuite|g' $CONF
    fi
done
#######################
# Get rid of default welcome page
#######################
# RedHat
if [ -f "/etc/httpd/conf.d/welcome.conf" ]; then
    mv -f /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.bak
fi
# Debian/Ubuntu
for CONF in /etc/apache2/sites-available/{default,default-ssl,000-default.conf,default-ssl.conf}; do
    if [ -f $CONF ]; then
       sed -i 's/DocumentRoot \/var\/www\(\/html\)\?$/DocumentRoot \/var\/www\/perfsonar/' $CONF
    fi
done

#######################
# Enable mod_rewite for ssl
#######################
# Debian/Ubuntu
for CONF in /etc/apache2/sites-available/{default,default-ssl,000-default.conf,default-ssl.conf}; do
    if [ -f $CONF ]; then
        grep -q RewriteEngine $CONF
        if [ $? -ne 0 ]; then
            sed -i 's/^\([[:space:]]*\)<\/VirtualHost>/\1    RewriteEngine on\n\1    RewriteOptions Inherit\n\1<\/VirtualHost>/' $CONF
        fi
    fi
done