#!/bin/bash
##########################################################################################
# ps-migrate-restore.sh <backup-tarball>
# 
# This script reads in a tarball file generated by "ps-migrate-backup" and places
# the files it contain at their required location.
# In its current form, the script does not backup any archive data.
#
# WARNING: This script may overwrite data on the target system. It is expected this script
# will be run on a freshly installed machine with no non-root users or existing data. 
# Use in the above cases at your own risk as you may lose  data or get unexpected results.
##########################################################################################

TEMP_BAK_NAME=ps-toolkit-migrate-backup
TEMP_RST_NAME=ps-toolkit-migrate-restore
TEMP_RST_DIR="/tmp/$TEMP_RST_NAME"

#Check parameters
TEMP=$(getopt -o d --long data -n $0 -- "$@")
if [ $? != 0 ]; then
    echo "Usage: $0 [-d|--data] <tgz-file>"
    echo "Unable to parse command line"
    exit 1
fi
eval set -- "$TEMP"

while true; do
   case "$1" in
       -d|--data) DATA=1 ; echo "This option is currently not available. Exiting..." ; exit 1 ; shift ;;
       --) shift ; break ;;
       *) echo "Internal error!" ; exit 1 ;;
   esac
done

#Check options
if [ -z "$1" ]; then
    echo "Usage: $0 [-d|--data] <tgz-file>"
    echo "Missing path to tar file in options list"
    exit 1
fi

#Create temp directory
rm -rf $TEMP_RST_DIR
mkdir -m 700 $TEMP_RST_DIR
if [ "$?" != "0" ]; then
    echo "Unable to create temp directory"
    exit 1
fi

#Unpack back up files
if [ -f "$1" ]; then
    tar -xzf $1 -C $TEMP_RST_DIR
else
    echo "File $1 does not exist"
    exit 1
fi

#get administrative info
printf "Restoring perfsonar configuration..."
cp -a $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/perfsonar/* /etc/perfsonar
if [ "$?" != "0" ]; then
    echo "Unable to restore /etc/perfsonar"
    exit 1
fi
printf "[SUCCESS]"
echo ""

#get owamp files
printf "Restoring owamp-server configuration..."
cp -a $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/owamp-server/* /etc/owamp-server
if [ "$?" != "0" ]; then
    echo "Unable to restore /etc/owamp-server"
    exit 1
fi
printf "[SUCCESS]"
echo ""

#get twamp files
if [ -d "$TEMP_RST_DIR/$TEMP_BAK_NAME/etc/twamp-server" ]; then
    printf "Restoring twamp-server configuration..."
    cp -a $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/twamp-server/* /etc/twamp-server
    if [ "$?" != "0" ]; then
        echo "Unable to restore /etc/twamp-server"
        exit 1
    fi
fi
printf "[SUCCESS]"
echo ""

#get NTP config
printf "Restoring NTP configuration..."
if [ -f "/etc/ntp.conf" ]; then
    #older systems
    cp $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/ntp.conf /etc/ntp.conf 
    if [ "$?" != "0" ]; then
        echo "Unable to restore /etc/ntp.conf"
        exit 1
    fi
    printf "[SUCCESS]"
    echo "" 
else
    if [ -f "/etc/ntpsec/ntp.conf" ]; then
        #new systems
		cp -a $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/ntpsec /etc/ntpsec
		if [ "$?" != "0" ]; then
            echo "Unable to restore /etc/ntpsec"
            exit 1
        fi
		printf "[SUCCESS]"
        echo ""
    else
        printf "[Unable to find NTP configuration]"
        echo ""
    fi
fi

#get chrony config if exists
printf "Restoring chrony configuration..."
if [ -d "$TEMP_RST_DIR/$TEMP_BAK_NAME/etc/chrony" ]; then
    if which chronyd > /dev/null; then
        cp -a $TEMP_RST_DIR/$TEMP_BAK_NAME/etc/chrony/*  /etc/chrony
        if [ "$?" != "0" ]; then
            echo "Unable to restore /etc/chrony"
            exit 1
        fi
        printf "[SUCCESS]"
        echo ""
	else
	    printf "[chrony is not installed in this host]"
		echo ""
	fi
fi

#get pscheduler if exists
PSCHEDULER_BACKUP=$TEMP_RST_DIR/$TEMP_BAK_NAME/pscheduler
if [ -e $PSCHEDULER_BACKUP ] && which pscheduler > /dev/null; then
    #new style restore
    pscheduler restore $PSCHEDULER_BACKUP
    if [ "$?" != "0" ]; then
        echo "Unable to restore pScheduler configuration"
        exit 1
    fi
fi

#Clean up temp directory
rm -rf $TEMP_RST_DIR
echo "Restore complete."
