#!/bin/bash
#
# A script to upgrade the firewall rules for pre-3.4 hosts

STORE_LOCATION=
LIVE_LOCATION=
STORE_VERSION=

while getopts  "l:s:v:" flag
do
    case "$flag" in
        l) LIVE_LOCATION=$OPTARG;;
        s) STORE_LOCATION=$OPTARG;;
        v) STORE_VERSION=$OPTARG;;
    esac
done

# Only upgrade the versions before 3.3
if [ `echo "${STORE_VERSION:0:3} < 3.4" | bc` -eq 0 ]; then
    exit 0
fi

/opt/perfsonar_ps/toolkit/scripts/system_environment/configure_firewall upgrade
