#!/bin/bash
#
# livecd_db_config	Initializes the  PostgreSQL database on a LiveCD.
#
# chkconfig: - 65 36
# description: LiveCD PostgreSQL database initializer.

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    case $ARG in
    start)
    if [ -f "/var/lib/pgsql/data/PG_VERSION" ]; then
        echo "Database looks initialized. Nothing to do."
    else
        rm -rf /var/lib/pgsql
        /opt/perfsonar_ps/toolkit/scripts/system_environment/configure_esmond
        /opt/perfsonar_ps/toolkit/scripts/system_environment/configure_regular_testing
    fi
	;;
    stop)
	;;
    restart)
    	$0 start
	;;
    *)
	echo "usage: $0 (start|stop|restart|help)"
	cat <<EOF

start      - initialize the database (if needed)
stop       - quietly do nothing. it's fun to pretend to be an init script.
restart    - same as start
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR