#!/bin/bash
#
# Init file to detect network interfaces and install DHCP config
#
# chkconfig: 2345 14 01
# description: Init file to detect network interfaces and install DHCP config
#

PREFIX=/opt/perfsonar_ps/toolkit
BINDIR=${PREFIX}/scripts

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    case $ARG in
    start)
	${BINDIR}/livecd_net_config.sh
	;;
    stop)
	;;
    *)
	echo "usage: $0 (start|stop|help)"
	cat <<EOF

start      - checks for new network interfaces
stop       - does nothing.
restart    - does nothing
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR
