#!/bin/bash
#######################
# Enable the Name Server Caching Daemon. Does not matter if this is running in
# an 'upgrade' or 'new install' context.
#######################

if type systemctl &>/dev/null; then
    systemctl enable --now nscd
else
    /sbin/chkconfig nscd on
fi
