#!/usr/bin/perl

use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/../lib";

use perfSONAR_PS::NPToolkit::Config::Services;
use perfSONAR_PS::NPToolkit::ConfigManager::Utils qw( restart_service );

my $datadir = "/var/lib/owamp";

system('find '.$datadir.' -type f -mtime +1 -exec rm {} \;');
restart_service( { name => "owamp" } );
