#!/bin/sh

BINDIR="$( readlink -f -- "$( dirname -- "$0" )" )"

/etc/init.d/mysqld status
if [ $? != 0 ]; then
    /etc/init.d/mysqld start
    STOP_MYSQL=1
fi

$BINDIR/initialize_cacti_database
$BINDIR/initialize_perfsonarbuoy_bwctl_database
$BINDIR/initialize_perfsonarbuoy_owamp_database
$BINDIR/initialize_traceroute_ma_database
$BINDIR/initialize_pinger_database

if [ "${STOP_MYSQL}" = "1" ]; then
    /etc/init.d/mysqld stop
fi
