#!/bin/sh

BINDIR="$( readlink -f -- "$( dirname -- "$0" )" )"

DB_NAME=cacti
DB_USERNAME=cactiuser
DB_PASSWORD=12NPT00LK1T

/etc/init.d/mysqld status
if [ $? != 0 ]; then
    /etc/init.d/mysqld start
    STOP_MYSQL=1
fi

if [ ! -e /var/lib/mysql/$DB_NAME ]; then
    mysql -u root -e "CREATE DATABASE $DB_NAME"
    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO $DB_USERNAME@localhost IDENTIFIED BY '$DB_PASSWORD'" $DB_NAME
    mysql -u root $DB_NAME < $BINDIR/cacti_toolkit_init.sql
fi

OUTPUT=`mysql -B -N -e "SELECT COUNT(*) FROM snmp_query_graph_rrd_sv WHERE text='|query_ifHighSpeed|000000';" cacti`
if [ $? != 0 -o "$OUTPUT" = "0" ]; then
    echo "Updating snmp_query_graph_rrd_sv"
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('7d7302e9a5b913d5f5ed501c30d2afb4',13,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('0abb3d524f6935d23c0ea94d27fe47b5',14,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('a4f638bbd029aa172d6f58089d1d6e56',20,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('f5871a808022d871d5ce6050fc2f5b6d',21,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('9b5d971a7cd4ffd025c1837e1ab50d35',16,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('168b632acba427ad8af62adabe9d6033',9,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
    mysql -e "INSERT INTO snmp_query_graph_rrd_sv (hash, snmp_query_graph_id, data_template_id, sequence, field_name, text) VALUES ('2cec3baeb1c96006501c5f6b373ed6a6',22,41,1,'rrd_maximum','|query_ifHighSpeed|000000');" cacti
fi

echo "Updating data_template_rrd"
mysql -e " UPDATE data_template_rrd SET rrd_maximum=10000000000 WHERE rrd_maximum='4294967295';" cacti

if [ "${STOP_MYSQL}" = "1" ]; then
    /etc/init.d/mysqld stop
fi
