#!/bin/bash
#######################
# Add /opt/perfsonar_ps/toolkit/scripts to everyone's path
#######################
cat >/etc/profile.d/add_toolkit_dirs.sh <<EOF

pathmunge () {
        if ! echo \$PATH | /bin/egrep -q "(^|:)\$1($|:)" ; then
           if [ "\$2" = "after" ] ; then
              PATH=\$PATH:\$1
           else
              PATH=\$1:\$PATH
           fi
        fi
}

pathmunge "/opt/perfsonar_ps/toolkit/scripts"
EOF
