#!/bin/bash
#######################
# Add /usr/dbxml-2.3.11/bin to everyone's path
#######################
cat >/etc/profile.d/add_dbxml_dir.sh <<EOF

pathmunge () {
        if ! echo \$PATH | /bin/egrep -q "(^|:)\$1($|:)" ; then
           if [ "\$2" = "after" ] ; then
              PATH=\$PATH:\$1
           else
              PATH=\$1:\$PATH
           fi
        fi
}

pathmunge "/usr/dbxml-2.3.11/bin"
EOF
