#!/bin/bash

#######################
# Disable the HTTP TRACE methods. Does not matter if this is running in an
# 'upgrade' or 'new install' context.
#######################
cat > /etc/httpd/conf.d/disable_trace.conf <<EOF
# Disables the HTTP TRACE method
TraceEnable      Off
EOF

#######################
# Disable weak SSL ciphers in Apache. Does not matter if this is running in an
# 'upgrade' or 'new install' context.
#######################

sed -i 's|SSLProtocol.*|SSLProtocol -ALL +TLSv1|g' /etc/httpd/conf.d/ssl.conf
sed -i 's|SSLCipherSuite.*|SSLCipherSuite ALL:!aNULL:!ADH:!DH:!EDH:!eNULL:-LOW:!EXP:RC4+RSA:+HIGH:-MEDIUM|g'  /etc/httpd/conf.d/ssl.conf

#######################
# Setup redirects so that if clients go to "http://[host]/" or
# "https://[host]/", they get redirected to "http://[host]/toolkit" or
# "https://[host]/toolkit". It writes a toolkit-specific file, and modifies
# ssl.conf only if it hasn't modified it already so it does not matter if this
# is running in an 'upgrade' or 'new install' context.
#######################
cat > /etc/httpd/conf.d/toolkit_root_redirect.conf <<EOF
# Redirects requests to "/" to "/toolkit". It's done in this strange way to
# avoid confusing people who enter an IP address and would get redirected to
# the hostname, or vice versa.
RewriteEngine     on
RewriteCond       %{HTTP_HOST} =""
RewriteRule       ^/$    http://%{SERVER_ADDR}/toolkit/

RewriteCond       %{HTTP_HOST} !=""
RewriteRule       ^/$    http://%{HTTP_HOST}/toolkit/
EOF

#######################
# Setup a redirect so that if clients go to "https://[host]/", they get
# redirected to "https://[host]/toolkit". this isn't done in the rpm so that
# users who just install the rpm don't have their root web url taken away.
#######################
grep RewriteEngine /etc/httpd/conf.d/ssl.conf &> /dev/null
if [ $? != 0 ]; then
sed -i 's|</VirtualHost>|RewriteEngine on\nRewriteOptions Inherit\n</VirtualHost>|g' /etc/httpd/conf.d/ssl.conf
fi

#######################
# Upgrade apache from the previous version (e.g. to make sure 'psadmin' stuff
# is in there and whatnot.
#######################
if [ "$1" == "upgrade" ]; then
    /opt/perfsonar_ps/toolkit/scripts/upgrade/upgrade_apache_admin
fi
