#!/bin/bash
#######################
# Set bwctl's output facility to 'local5', the same as owamp's default
#######################
grep ^facility /etc/bwctld/bwctld.conf &> /dev/null
if [ $? != 0 ]; then
cat >>/etc/bwctld/bwctld.conf <<EOF
facility        local5
EOF
fi
