#!/bin/bash
#######################
# Set bwctl's output facility to 'local5', the same as owamp's default
#######################
grep ^facility /etc/bwctl-server/bwctl-server.conf &> /dev/null
if [ $? != 0 ]; then
cat >>/etc/bwctl-server/bwctl-server.conf <<EOF

facility        local5
EOF
fi
