#!/bin/bash
####################
# Configure default NTP servers for first boot.
####################

file=/etc/ntp/step-tickers

if [ ! -s $file ]; then
cat >$file <<EOF
owamp.chic.net.internet2.edu 
owamp.hous.net.internet2.edu
owamp.losa.net.internet2.edu
owamp.newy.net.internet2.edu 
chronos.es.net
saturn.es.net
EOF
fi

