#!/bin/bash
#######################
# Disable weak SSL ciphers in Apache. Does not matter if this is running in an
# 'upgrade' or 'new install' context.
#######################

sed -i 's|SSLProtocol.*|SSLProtocol All -SSLv2 -SSLv3|g' /etc/httpd/conf.d/ssl.conf
sed -i 's|SSLCipherSuite.*|SSLCipherSuite AES:!kRSA:!aNULL|g'  /etc/httpd/conf.d/ssl.conf
