#!/bin/bash
#######################
# Override the owampd.conf to make sure that the disk limit to 1G from the
# default of 10M.
#######################
if [ "$1" == "new" ]; then
cat >/etc/owampd/owampd.limits <<EOF
limit root with delete_on_fetch=on, bandwidth=0, disk=0, allow_open_mode=on
limit regular with delete_on_fetch=on, parent=root, bandwidth=10M, disk=1G, allow_open_mode=on
limit jail with parent=root, bandwidth=1, disk=1, allow_open_mode=off
assign default regular
EOF
fi

if [ "$1" == "upgrade" ]; then
# Up the owampd limits from 1M to 10M if they were using the default limits
sed -r -i 's/(.*limit regular.*)bandwidth=1000000,/\1bandwidth=10M,/g' /etc/owampd/owampd.limits

# Increase readability of the 1G limit in the previous default
sed -i 's/1073741824,/1G,/g' /etc/owampd/owampd.limits
fi
